// Code generated by mockery. DO NOT EDIT.

//go:build !compile

package api

import (
	context "context"
	json "encoding/json"

	kv "github.com/ksysoev/mimir/pkg/repo/kv"

	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CheckHealth provides a mock function with given fields: ctx
func (_m *MockService) CheckHealth(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CheckHealth")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_CheckHealth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckHealth'
type MockService_CheckHealth_Call struct {
	*mock.Call
}

// CheckHealth is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) CheckHealth(ctx interface{}) *MockService_CheckHealth_Call {
	return &MockService_CheckHealth_Call{Call: _e.mock.On("CheckHealth", ctx)}
}

func (_c *MockService_CheckHealth_Call) Run(run func(ctx context.Context)) *MockService_CheckHealth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_CheckHealth_Call) Return(_a0 error) *MockService_CheckHealth_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_CheckHealth_Call) RunAndReturn(run func(context.Context) error) *MockService_CheckHealth_Call {
	_c.Call.Return(run)
	return _c
}

// GetKey provides a mock function with given fields: ctx, key
func (_m *MockService) GetKey(ctx context.Context, key string) (kv.Item, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetKey")
	}

	var r0 kv.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (kv.Item, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) kv.Item); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(kv.Item)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKey'
type MockService_GetKey_Call struct {
	*mock.Call
}

// GetKey is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockService_Expecter) GetKey(ctx interface{}, key interface{}) *MockService_GetKey_Call {
	return &MockService_GetKey_Call{Call: _e.mock.On("GetKey", ctx, key)}
}

func (_c *MockService_GetKey_Call) Run(run func(ctx context.Context, key string)) *MockService_GetKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_GetKey_Call) Return(_a0 kv.Item, _a1 error) *MockService_GetKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetKey_Call) RunAndReturn(run func(context.Context, string) (kv.Item, error)) *MockService_GetKey_Call {
	_c.Call.Return(run)
	return _c
}

// PatchKey provides a mock function with given fields: ctx, key, delta, ifVersion
func (_m *MockService) PatchKey(ctx context.Context, key string, delta json.RawMessage, ifVersion *int64) (kv.Item, error) {
	ret := _m.Called(ctx, key, delta, ifVersion)

	if len(ret) == 0 {
		panic("no return value specified for PatchKey")
	}

	var r0 kv.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, json.RawMessage, *int64) (kv.Item, error)); ok {
		return rf(ctx, key, delta, ifVersion)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, json.RawMessage, *int64) kv.Item); ok {
		r0 = rf(ctx, key, delta, ifVersion)
	} else {
		r0 = ret.Get(0).(kv.Item)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, json.RawMessage, *int64) error); ok {
		r1 = rf(ctx, key, delta, ifVersion)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_PatchKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PatchKey'
type MockService_PatchKey_Call struct {
	*mock.Call
}

// PatchKey is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - delta json.RawMessage
//   - ifVersion *int64
func (_e *MockService_Expecter) PatchKey(ctx interface{}, key interface{}, delta interface{}, ifVersion interface{}) *MockService_PatchKey_Call {
	return &MockService_PatchKey_Call{Call: _e.mock.On("PatchKey", ctx, key, delta, ifVersion)}
}

func (_c *MockService_PatchKey_Call) Run(run func(ctx context.Context, key string, delta json.RawMessage, ifVersion *int64)) *MockService_PatchKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(json.RawMessage), args[3].(*int64))
	})
	return _c
}

func (_c *MockService_PatchKey_Call) Return(_a0 kv.Item, _a1 error) *MockService_PatchKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_PatchKey_Call) RunAndReturn(run func(context.Context, string, json.RawMessage, *int64) (kv.Item, error)) *MockService_PatchKey_Call {
	_c.Call.Return(run)
	return _c
}

// PutKey provides a mock function with given fields: ctx, key, value, ifVersion
func (_m *MockService) PutKey(ctx context.Context, key string, value json.RawMessage, ifVersion *int64) (kv.Item, error) {
	ret := _m.Called(ctx, key, value, ifVersion)

	if len(ret) == 0 {
		panic("no return value specified for PutKey")
	}

	var r0 kv.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, json.RawMessage, *int64) (kv.Item, error)); ok {
		return rf(ctx, key, value, ifVersion)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, json.RawMessage, *int64) kv.Item); ok {
		r0 = rf(ctx, key, value, ifVersion)
	} else {
		r0 = ret.Get(0).(kv.Item)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, json.RawMessage, *int64) error); ok {
		r1 = rf(ctx, key, value, ifVersion)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_PutKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutKey'
type MockService_PutKey_Call struct {
	*mock.Call
}

// PutKey is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value json.RawMessage
//   - ifVersion *int64
func (_e *MockService_Expecter) PutKey(ctx interface{}, key interface{}, value interface{}, ifVersion interface{}) *MockService_PutKey_Call {
	return &MockService_PutKey_Call{Call: _e.mock.On("PutKey", ctx, key, value, ifVersion)}
}

func (_c *MockService_PutKey_Call) Run(run func(ctx context.Context, key string, value json.RawMessage, ifVersion *int64)) *MockService_PutKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(json.RawMessage), args[3].(*int64))
	})
	return _c
}

func (_c *MockService_PutKey_Call) Return(_a0 kv.Item, _a1 error) *MockService_PutKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_PutKey_Call) RunAndReturn(run func(context.Context, string, json.RawMessage, *int64) (kv.Item, error)) *MockService_PutKey_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
