// Code generated by mockery. DO NOT EDIT.

//go:build !compile

package api

import (
	context "context"

	core "github.com/ksysoev/mimir/pkg/core"
	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CheckHealth provides a mock function with given fields: ctx
func (_m *MockService) CheckHealth(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CheckHealth")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_CheckHealth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckHealth'
type MockService_CheckHealth_Call struct {
	*mock.Call
}

// CheckHealth is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) CheckHealth(ctx interface{}) *MockService_CheckHealth_Call {
	return &MockService_CheckHealth_Call{Call: _e.mock.On("CheckHealth", ctx)}
}

func (_c *MockService_CheckHealth_Call) Run(run func(ctx context.Context)) *MockService_CheckHealth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_CheckHealth_Call) Return(_a0 error) *MockService_CheckHealth_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_CheckHealth_Call) RunAndReturn(run func(context.Context) error) *MockService_CheckHealth_Call {
	_c.Call.Return(run)
	return _c
}

// GetKey provides a mock function with given fields: ctx, key
func (_m *MockService) GetKey(ctx context.Context, key string) (core.Item, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetKey")
	}

	var r0 core.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (core.Item, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) core.Item); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(core.Item)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKey'
type MockService_GetKey_Call struct {
	*mock.Call
}

// GetKey is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockService_Expecter) GetKey(ctx interface{}, key interface{}) *MockService_GetKey_Call {
	return &MockService_GetKey_Call{Call: _e.mock.On("GetKey", ctx, key)}
}

func (_c *MockService_GetKey_Call) Run(run func(ctx context.Context, key string)) *MockService_GetKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_GetKey_Call) Return(_a0 core.Item, _a1 error) *MockService_GetKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetKey_Call) RunAndReturn(run func(context.Context, string) (core.Item, error)) *MockService_GetKey_Call {
	_c.Call.Return(run)
	return _c
}

// ListKeys provides a mock function with given fields: ctx, nodeID
func (_m *MockService) ListKeys(ctx context.Context, nodeID string) []core.KeyEntry {
	ret := _m.Called(ctx, nodeID)

	if len(ret) == 0 {
		panic("no return value specified for ListKeys")
	}

	var r0 []core.KeyEntry
	if rf, ok := ret.Get(0).(func(context.Context, string) []core.KeyEntry); ok {
		r0 = rf(ctx, nodeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]core.KeyEntry)
		}
	}

	return r0
}

// MockService_ListKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListKeys'
type MockService_ListKeys_Call struct {
	*mock.Call
}

// ListKeys is a helper method to define mock.On call
//   - ctx context.Context
//   - nodeID string
func (_e *MockService_Expecter) ListKeys(ctx interface{}, nodeID interface{}) *MockService_ListKeys_Call {
	return &MockService_ListKeys_Call{Call: _e.mock.On("ListKeys", ctx, nodeID)}
}

func (_c *MockService_ListKeys_Call) Run(run func(ctx context.Context, nodeID string)) *MockService_ListKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_ListKeys_Call) Return(_a0 []core.KeyEntry) *MockService_ListKeys_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_ListKeys_Call) RunAndReturn(run func(context.Context, string) []core.KeyEntry) *MockService_ListKeys_Call {
	_c.Call.Return(run)
	return _c
}

// PatchKey provides a mock function with given fields: ctx, item
func (_m *MockService) PatchKey(ctx context.Context, item core.Item) (core.Item, error) {
	ret := _m.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for PatchKey")
	}

	var r0 core.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, core.Item) (core.Item, error)); ok {
		return rf(ctx, item)
	}
	if rf, ok := ret.Get(0).(func(context.Context, core.Item) core.Item); ok {
		r0 = rf(ctx, item)
	} else {
		r0 = ret.Get(0).(core.Item)
	}

	if rf, ok := ret.Get(1).(func(context.Context, core.Item) error); ok {
		r1 = rf(ctx, item)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_PatchKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PatchKey'
type MockService_PatchKey_Call struct {
	*mock.Call
}

// PatchKey is a helper method to define mock.On call
//   - ctx context.Context
//   - item core.Item
func (_e *MockService_Expecter) PatchKey(ctx interface{}, item interface{}) *MockService_PatchKey_Call {
	return &MockService_PatchKey_Call{Call: _e.mock.On("PatchKey", ctx, item)}
}

func (_c *MockService_PatchKey_Call) Run(run func(ctx context.Context, item core.Item)) *MockService_PatchKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(core.Item))
	})
	return _c
}

func (_c *MockService_PatchKey_Call) Return(_a0 core.Item, _a1 error) *MockService_PatchKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_PatchKey_Call) RunAndReturn(run func(context.Context, core.Item) (core.Item, error)) *MockService_PatchKey_Call {
	_c.Call.Return(run)
	return _c
}

// PutKey provides a mock function with given fields: ctx, item
func (_m *MockService) PutKey(ctx context.Context, item core.Item) (core.Item, error) {
	ret := _m.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for PutKey")
	}

	var r0 core.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, core.Item) (core.Item, error)); ok {
		return rf(ctx, item)
	}
	if rf, ok := ret.Get(0).(func(context.Context, core.Item) core.Item); ok {
		r0 = rf(ctx, item)
	} else {
		r0 = ret.Get(0).(core.Item)
	}

	if rf, ok := ret.Get(1).(func(context.Context, core.Item) error); ok {
		r1 = rf(ctx, item)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_PutKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutKey'
type MockService_PutKey_Call struct {
	*mock.Call
}

// PutKey is a helper method to define mock.On call
//   - ctx context.Context
//   - item core.Item
func (_e *MockService_Expecter) PutKey(ctx interface{}, item interface{}) *MockService_PutKey_Call {
	return &MockService_PutKey_Call{Call: _e.mock.On("PutKey", ctx, item)}
}

func (_c *MockService_PutKey_Call) Run(run func(ctx context.Context, item core.Item)) *MockService_PutKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(core.Item))
	})
	return _c
}

func (_c *MockService_PutKey_Call) Return(_a0 core.Item, _a1 error) *MockService_PutKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_PutKey_Call) RunAndReturn(run func(context.Context, core.Item) (core.Item, error)) *MockService_PutKey_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
