// Code generated by mockery. DO NOT EDIT.

//go:build !compile

package core

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockkvStore is an autogenerated mock type for the kvStore type
type MockkvStore struct {
	mock.Mock
}

type MockkvStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockkvStore) EXPECT() *MockkvStore_Expecter {
	return &MockkvStore_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, key
func (_m *MockkvStore) Get(ctx context.Context, key string) (Item, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (Item, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) Item); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(Item)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockkvStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockkvStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockkvStore_Expecter) Get(ctx interface{}, key interface{}) *MockkvStore_Get_Call {
	return &MockkvStore_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockkvStore_Get_Call) Run(run func(ctx context.Context, key string)) *MockkvStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockkvStore_Get_Call) Return(_a0 Item, _a1 error) *MockkvStore_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockkvStore_Get_Call) RunAndReturn(run func(context.Context, string) (Item, error)) *MockkvStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function with given fields: ctx, key, value, contentType, ifVersion
func (_m *MockkvStore) Put(ctx context.Context, key string, value []byte, contentType string, ifVersion *int64) (Item, error) {
	ret := _m.Called(ctx, key, value, contentType, ifVersion)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte, string, *int64) (Item, error)); ok {
		return rf(ctx, key, value, contentType, ifVersion)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte, string, *int64) Item); ok {
		r0 = rf(ctx, key, value, contentType, ifVersion)
	} else {
		r0 = ret.Get(0).(Item)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []byte, string, *int64) error); ok {
		r1 = rf(ctx, key, value, contentType, ifVersion)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockkvStore_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockkvStore_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value []byte
//   - contentType string
//   - ifVersion *int64
func (_e *MockkvStore_Expecter) Put(ctx interface{}, key interface{}, value interface{}, contentType interface{}, ifVersion interface{}) *MockkvStore_Put_Call {
	return &MockkvStore_Put_Call{Call: _e.mock.On("Put", ctx, key, value, contentType, ifVersion)}
}

func (_c *MockkvStore_Put_Call) Run(run func(ctx context.Context, key string, value []byte, contentType string, ifVersion *int64)) *MockkvStore_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte), args[3].(string), args[4].(*int64))
	})
	return _c
}

func (_c *MockkvStore_Put_Call) Return(_a0 Item, _a1 error) *MockkvStore_Put_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockkvStore_Put_Call) RunAndReturn(run func(context.Context, string, []byte, string, *int64) (Item, error)) *MockkvStore_Put_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockkvStore creates a new instance of MockkvStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockkvStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockkvStore {
	mock := &MockkvStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
