// Code generated by mockery. DO NOT EDIT.

//go:build !compile

package core

import (
	json "encoding/json"

	kv "github.com/ksysoev/mimir/pkg/repo/kv"
	mock "github.com/stretchr/testify/mock"
)

// MockkvStore is an autogenerated mock type for the kvStore type
type MockkvStore struct {
	mock.Mock
}

type MockkvStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockkvStore) EXPECT() *MockkvStore_Expecter {
	return &MockkvStore_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: key
func (_m *MockkvStore) Get(key string) (kv.Item, error) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 kv.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (kv.Item, error)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) kv.Item); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(kv.Item)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockkvStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockkvStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *MockkvStore_Expecter) Get(key interface{}) *MockkvStore_Get_Call {
	return &MockkvStore_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *MockkvStore_Get_Call) Run(run func(key string)) *MockkvStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockkvStore_Get_Call) Return(_a0 kv.Item, _a1 error) *MockkvStore_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockkvStore_Get_Call) RunAndReturn(run func(string) (kv.Item, error)) *MockkvStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Patch provides a mock function with given fields: key, delta, ifVersion
func (_m *MockkvStore) Patch(key string, delta json.RawMessage, ifVersion *int64) (kv.Item, error) {
	ret := _m.Called(key, delta, ifVersion)

	if len(ret) == 0 {
		panic("no return value specified for Patch")
	}

	var r0 kv.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(string, json.RawMessage, *int64) (kv.Item, error)); ok {
		return rf(key, delta, ifVersion)
	}
	if rf, ok := ret.Get(0).(func(string, json.RawMessage, *int64) kv.Item); ok {
		r0 = rf(key, delta, ifVersion)
	} else {
		r0 = ret.Get(0).(kv.Item)
	}

	if rf, ok := ret.Get(1).(func(string, json.RawMessage, *int64) error); ok {
		r1 = rf(key, delta, ifVersion)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockkvStore_Patch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Patch'
type MockkvStore_Patch_Call struct {
	*mock.Call
}

// Patch is a helper method to define mock.On call
//   - key string
//   - delta json.RawMessage
//   - ifVersion *int64
func (_e *MockkvStore_Expecter) Patch(key interface{}, delta interface{}, ifVersion interface{}) *MockkvStore_Patch_Call {
	return &MockkvStore_Patch_Call{Call: _e.mock.On("Patch", key, delta, ifVersion)}
}

func (_c *MockkvStore_Patch_Call) Run(run func(key string, delta json.RawMessage, ifVersion *int64)) *MockkvStore_Patch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(json.RawMessage), args[2].(*int64))
	})
	return _c
}

func (_c *MockkvStore_Patch_Call) Return(_a0 kv.Item, _a1 error) *MockkvStore_Patch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockkvStore_Patch_Call) RunAndReturn(run func(string, json.RawMessage, *int64) (kv.Item, error)) *MockkvStore_Patch_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function with given fields: key, value, ifVersion
func (_m *MockkvStore) Put(key string, value json.RawMessage, ifVersion *int64) (kv.Item, error) {
	ret := _m.Called(key, value, ifVersion)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 kv.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(string, json.RawMessage, *int64) (kv.Item, error)); ok {
		return rf(key, value, ifVersion)
	}
	if rf, ok := ret.Get(0).(func(string, json.RawMessage, *int64) kv.Item); ok {
		r0 = rf(key, value, ifVersion)
	} else {
		r0 = ret.Get(0).(kv.Item)
	}

	if rf, ok := ret.Get(1).(func(string, json.RawMessage, *int64) error); ok {
		r1 = rf(key, value, ifVersion)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockkvStore_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockkvStore_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - key string
//   - value json.RawMessage
//   - ifVersion *int64
func (_e *MockkvStore_Expecter) Put(key interface{}, value interface{}, ifVersion interface{}) *MockkvStore_Put_Call {
	return &MockkvStore_Put_Call{Call: _e.mock.On("Put", key, value, ifVersion)}
}

func (_c *MockkvStore_Put_Call) Run(run func(key string, value json.RawMessage, ifVersion *int64)) *MockkvStore_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(json.RawMessage), args[2].(*int64))
	})
	return _c
}

func (_c *MockkvStore_Put_Call) Return(_a0 kv.Item, _a1 error) *MockkvStore_Put_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockkvStore_Put_Call) RunAndReturn(run func(string, json.RawMessage, *int64) (kv.Item, error)) *MockkvStore_Put_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockkvStore creates a new instance of MockkvStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockkvStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockkvStore {
	mock := &MockkvStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
