// Code generated by mockery. DO NOT EDIT.

//go:build !compile

package core

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockkvStore is an autogenerated mock type for the kvStore type
type MockkvStore struct {
	mock.Mock
}

type MockkvStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockkvStore) EXPECT() *MockkvStore_Expecter {
	return &MockkvStore_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, key
func (_m *MockkvStore) Get(ctx context.Context, key string) (Item, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (Item, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) Item); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(Item)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockkvStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockkvStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockkvStore_Expecter) Get(ctx interface{}, key interface{}) *MockkvStore_Get_Call {
	return &MockkvStore_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockkvStore_Get_Call) Run(run func(ctx context.Context, key string)) *MockkvStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockkvStore_Get_Call) Return(_a0 Item, _a1 error) *MockkvStore_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockkvStore_Get_Call) RunAndReturn(run func(context.Context, string) (Item, error)) *MockkvStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// ListKeys provides a mock function with given fields: ctx
func (_m *MockkvStore) ListKeys(ctx context.Context) []string {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListKeys")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// MockkvStore_ListKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListKeys'
type MockkvStore_ListKeys_Call struct {
	*mock.Call
}

// ListKeys is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockkvStore_Expecter) ListKeys(ctx interface{}) *MockkvStore_ListKeys_Call {
	return &MockkvStore_ListKeys_Call{Call: _e.mock.On("ListKeys", ctx)}
}

func (_c *MockkvStore_ListKeys_Call) Run(run func(ctx context.Context)) *MockkvStore_ListKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockkvStore_ListKeys_Call) Return(_a0 []string) *MockkvStore_ListKeys_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockkvStore_ListKeys_Call) RunAndReturn(run func(context.Context) []string) *MockkvStore_ListKeys_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function with given fields: ctx, item
func (_m *MockkvStore) Put(ctx context.Context, item Item) (Item, error) {
	ret := _m.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, Item) (Item, error)); ok {
		return rf(ctx, item)
	}
	if rf, ok := ret.Get(0).(func(context.Context, Item) Item); ok {
		r0 = rf(ctx, item)
	} else {
		r0 = ret.Get(0).(Item)
	}

	if rf, ok := ret.Get(1).(func(context.Context, Item) error); ok {
		r1 = rf(ctx, item)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockkvStore_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockkvStore_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - item Item
func (_e *MockkvStore_Expecter) Put(ctx interface{}, item interface{}) *MockkvStore_Put_Call {
	return &MockkvStore_Put_Call{Call: _e.mock.On("Put", ctx, item)}
}

func (_c *MockkvStore_Put_Call) Run(run func(ctx context.Context, item Item)) *MockkvStore_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(Item))
	})
	return _c
}

func (_c *MockkvStore_Put_Call) Return(_a0 Item, _a1 error) *MockkvStore_Put_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockkvStore_Put_Call) RunAndReturn(run func(context.Context, Item) (Item, error)) *MockkvStore_Put_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockkvStore creates a new instance of MockkvStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockkvStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockkvStore {
	mock := &MockkvStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
